(*
  CRC_Functions

  When active, the CRC functions are available for use, otherwise they are
  removed from the library.

  Default: active
*)
{$DEFINE CRC_Functions}

(*
  VER_1_0_3

  When active, the library uses version 1.0.3 of the CityHash implementation.
  Otherwise the version 1.1.1 is used.

  Default: inactive
*)
{$DEFINE VER_1_0_3}

//------------------------------------------------------------------------------

// Do not change following lines
{$Q-}
{$R-}
